# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2018-11-04')),
                ('due_date', models.DateField(default='2018-11-04')),
                ('category', models.ForeignKey(default='Sachin', on_delete=django.db.models.deletion.CASCADE, to='toodo.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
