# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0002_auto_20181104_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='document',
            field=models.FileField(default='sss', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
