# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-04 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0003_todo_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='document',
        ),
    ]
