# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0004_remove_todo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(default='sss', on_delete=django.db.models.deletion.CASCADE, to='toodo.Category'),
        ),
    ]
