# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-05 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0009_auto_20181105_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contact_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
