# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0010_auto_20181105_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
